### ISSUE TITLE
Review for set up Kanban board

### ISSUE THREAD

**Issue by ahzia** [ahzia/rails-recipe-app#6]
here is our GitHub project link:
https://github.com/ahzia/rails-recipe-app/projects/1
kindly check it and share your feedback.

**Comment by dasileker** [comment]
## **Hi @ahzia,** 

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ahzia** [comment]
@dasileker Thanks for the review
